theme: jekyll-theme-minimal
title: "Your Name — RTL Design Engineer"
description: "RTL design, cache compression, CPU microarchitecture, and verification."
logo: /assets/profile.png
show_downloads: false
google_analytics:
