title: "Shubham Deepak Lonkar"
description: "RTL Design - CPU Microarchitecture"
theme: jekyll-theme-slate
logo: /assets/profile.png
show_downloads: false
navigation:

    title: Home
    url: /

    title: Projects
    url: /projects/

    title: Experience
    url: /#experience

    title: Skills
    url: /#skills

    title: Education
    url: /#education

    title: Writing
    url: /#writing

    title: Contact
    url: /#contact
