title: "Shubham D. Lonkar"
description: "ASIC Design Engineer | RTL Design | Low-Power | Functional Verification"
theme: jekyll-theme-slate
show_downloads: false
navigation:
  - title: Experience
    url: /#experience
  - title: Skills
    url: /#skills
  - title: Projects
    url: /#projects
  - title: Research
    url: /#research
